import { AnimeTrack } from './types';

export const INITIAL_TRACKS: AnimeTrack[] = [
  {
    id: 'tr_1',
    title: "A Cruel Angel's Thesis",
    artist: 'Yoko Takahashi',
    animeName: 'Neon Genesis Evangelion',
    type: 'OP',
    youtubeId: 't-QSmNReDyI',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_2',
    title: 'Unravel',
    artist: 'TK from Ling tosite sigure',
    animeName: 'Tokyo Ghoul',
    type: 'OP',
    youtubeId: 'Fve_l8I0Ayk',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_3',
    title: 'Again',
    artist: 'YUI',
    animeName: 'Fullmetal Alchemist: Brotherhood',
    type: 'OP',
    youtubeId: '5M6Gv4kAgQk',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_4',
    title: 'Gurenge',
    artist: 'LiSA',
    animeName: 'Demon Slayer',
    type: 'OP',
    youtubeId: 'op_c_5_9I_o',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_5',
    title: 'The Hero!!',
    artist: 'JAM Project',
    animeName: 'One Punch Man',
    type: 'OP',
    youtubeId: 'QImBolnTV6s',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_6',
    title: 'Silhouette',
    artist: 'KANA-BOON',
    animeName: 'Naruto Shippuden',
    type: 'OP',
    youtubeId: 'dlFA0Zq1k2g',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_7',
    title: 'Shinzou wo Sasageyo!',
    artist: 'Linked Horizon',
    animeName: 'Attack on Titan',
    type: 'OP',
    youtubeId: '86K0f0S1Xf8',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_8',
    title: 'Kaikai Kitan',
    artist: 'Eve',
    animeName: 'Jujutsu Kaisen',
    type: 'OP',
    youtubeId: 'v8b3YrokKxg',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_9',
    title: 'Kick Back',
    artist: 'Kenshi Yonezu',
    animeName: 'Chainsaw Man',
    type: 'OP',
    youtubeId: 'M2cckDmNLMI',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_10',
    title: 'Idol',
    artist: 'YOASOBI',
    animeName: 'Oshi no Ko',
    type: 'OP',
    youtubeId: 'ZRtdQ81jPUQ',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_11',
    title: 'Fly High!!',
    artist: 'Burnout Syndromes',
    animeName: 'Haikyuu!!',
    type: 'OP',
    youtubeId: 'as_D_LzF3_M',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_12',
    title: 'Brave Shine',
    artist: 'Aimer',
    animeName: 'Fate/stay night [UBW]',
    type: 'OP',
    youtubeId: 'R_v_p_-b29M',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_13',
    title: 'Blue Bird',
    artist: 'Ikimonogakari',
    animeName: 'Naruto Shippuden',
    type: 'OP',
    youtubeId: 'KpsJWFuOPdY',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_14',
    title: 'Renai Circulation',
    artist: 'Kana Hanazawa',
    animeName: 'Bakemonogatari',
    type: 'OP',
    youtubeId: '8D_8X_N10R4',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_15',
    title: 'Crossing Field',
    artist: 'LiSA',
    animeName: 'Sword Art Online',
    type: 'OP',
    youtubeId: 'uKxyLmbY68M',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_16',
    title: 'Sugar Song to Bitter Step',
    artist: 'Unison Square Garden',
    animeName: 'Kekkai Sensen',
    type: 'ED',
    youtubeId: 'Z6sJXhLqS8U',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_17',
    title: 'Lost in Paradise',
    artist: 'ALI feat. AKLO',
    animeName: 'Jujutsu Kaisen',
    type: 'ED',
    youtubeId: '6riDJDg-Ym0',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_18',
    title: 'Don\'t Say "Lazy"',
    artist: 'Sakurakou K-On Bu',
    animeName: 'K-On!',
    type: 'ED',
    youtubeId: 'l8S7qH3n7q4',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_19',
    title: 'Hare Hare Yukai',
    artist: 'Aya Hirano, Minori Chihara, Yuko Goto',
    animeName: 'The Melancholy of Haruhi Suzumiya',
    type: 'ED',
    youtubeId: 'c5G5bS_f20A',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_20',
    title: 'Fly Me to the Moon',
    artist: 'CLAIRE',
    animeName: 'Neon Genesis Evangelion',
    type: 'ED',
    youtubeId: 'oZ0rVIdVveY', // clear TV size
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_21',
    title: 'Hunting for Your Dream',
    artist: 'Galneryus',
    animeName: 'Hunter x Hunter (2011)',
    type: 'ED',
    youtubeId: 'gZ-Iu4i6lGk',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_22',
    title: 'Wind',
    artist: 'Akeboshi',
    animeName: 'Naruto',
    type: 'ED',
    youtubeId: 'I6p-oI7w2-Y',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_23',
    title: 'Sadness and Sorrow',
    artist: 'Toshio Masuda',
    animeName: 'Naruto',
    type: 'OST',
    youtubeId: 'wEWF2rx5XXg',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_24',
    title: 'YouSeeBIGGIRL/T:T',
    artist: 'Hiroyuki Sawano',
    animeName: 'Attack on Titan',
    type: 'OST',
    youtubeId: 'r4Um6okMHcM',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_25',
    title: 'L\'s Theme',
    artist: 'Yoshihisa Hirano',
    animeName: 'Death Note',
    type: 'OST',
    youtubeId: 'MTGLt4S-EIE',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_26',
    title: 'Swordland',
    artist: 'Yuki Kajiura',
    animeName: 'Sword Art Online',
    type: 'OST',
    youtubeId: 'vK4g7_pI6wM',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_27',
    title: 'Fairy Tail Main Theme',
    artist: 'Yasuharu Takanashi',
    animeName: 'Fairy Tail',
    type: 'OST',
    youtubeId: 'ksc2-0sO5YI',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_28',
    title: 'Number One',
    artist: 'Shiro Sagisu',
    animeName: 'Bleach',
    type: 'OST',
    youtubeId: '3t8rDleV8vE',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_29',
    title: 'Next To You',
    artist: 'Ken Arai',
    animeName: 'Parasyte -the maxim-',
    type: 'OST',
    youtubeId: '4gIq8E9lT5c',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  },
  {
    id: 'tr_30',
    title: 'Decretum',
    artist: 'Yuki Kajiura',
    animeName: 'Puella Magi Madoka Magica',
    type: 'OST',
    youtubeId: '1U5K8QZ-b5M',
    elo: 1200,
    matchesPlayed: 0,
    wins: 0,
    losses: 0,
    draws: 0
  }
];
