import { AnimeTrack } from './types';

export const SEEDED_TRACKS: Omit<AnimeTrack, 'id' | 'elo' | 'matchesPlayed' | 'wins' | 'losses' | 'draws'>[] = [
  {
    title: "Specialz",
    artist: "King Gnu",
    animeName: "Jujutsu Kaisen Season 2",
    type: "OP",
    youtubeId: "ldEzCnE89a4",
    addedByUser: false,
  },
  {
    title: "Bling-Bang-Bang-Born",
    artist: "Creepy Nuts",
    animeName: "Mashle: Magic and Muscles",
    type: "OP",
    youtubeId: "210R0ozmLwg",
    addedByUser: false,
  },
  {
    title: "Kura Kura",
    artist: "Ado",
    animeName: "Spy x Family",
    type: "OP",
    youtubeId: "WO0Ko2A0sLM",
    addedByUser: false,
  },
  {
    title: "Hollow Hunger",
    artist: "OxT",
    animeName: "Overlord IV",
    type: "OP",
    youtubeId: "bkHQ_rNcK7g",
    addedByUser: false,
  },
  {
    title: "Inferno",
    artist: "Mrs. GREEN APPLE",
    animeName: "Fire Force",
    type: "OP",
    youtubeId: "qfzT4yBKQ5w",
    addedByUser: false,
  },
  {
    title: "Guren no Yumiya",
    artist: "Linked Horizon",
    animeName: "Attack on Titan",
    type: "OP",
    youtubeId: "Pn7dCgtwX2c",
    addedByUser: false,
  },
  {
    title: "We Are!",
    artist: "Hiroshi Kitadani",
    animeName: "One Piece",
    type: "OP",
    youtubeId: "nqb2x_94hK0",
    addedByUser: false,
  },
  {
    title: "Kizuna no Kiseki",
    artist: "MAN WITH A MISSION x milet",
    animeName: "Demon Slayer: Swordsmith Village Arc",
    type: "OP",
    youtubeId: "dTDzDxv-YDo",
    addedByUser: false,
  },
  {
    title: "Peace Sign",
    artist: "Kenshi Yonezu",
    animeName: "My Hero Academia",
    type: "OP",
    youtubeId: "9aJVr5tTTWk",
    addedByUser: false,
  },
  {
    title: "Anytime Anywhere",
    artist: "milet",
    animeName: "Frieren: Beyond Journey's End",
    type: "ED",
    youtubeId: "mZD6xxq-eyI",
    addedByUser: false,
  },
  {
    title: "Haruka Kanata",
    artist: "ASIAN KUNG-FU GENERATION",
    animeName: "Naruto",
    type: "OP",
    youtubeId: "slq_YcCI5xk",
    addedByUser: false,
  },
  {
    title: "Guren",
    artist: "DOES",
    animeName: "Naruto Shippuden",
    type: "OP",
    youtubeId: "gwOeV2umUb4",
    addedByUser: false,
  },
  {
    title: "My Dearest",
    artist: "Supercell",
    animeName: "Guilty Crown",
    type: "OP",
    youtubeId: "DjUtmbZt8zc",
    addedByUser: false,
  },
  {
    title: "Cruel Clad in Scarlet",
    artist: "Yutaka Yamada",
    animeName: "Tokyo Ghoul",
    type: "OST",
    youtubeId: "3S1NmtWDVYk",
    addedByUser: false,
  },
  {
    title: "This Game",
    artist: "Konomi Suzuki",
    animeName: "No Game No Life",
    type: "OP",
    youtubeId: "ZaDpKGSAPrk",
    addedByUser: false,
  },
  {
    title: "Colors",
    artist: "Flow",
    animeName: "Code Geass",
    type: "OP",
    youtubeId: "OLVyJl87_CI",
    addedByUser: false,
  },
  {
    title: "The Melancholy of Haruhi Suzumiya OST",
    artist: "Satoru Kousaki",
    animeName: "The Melancholy of Haruhi Suzumiya",
    type: "OST",
    youtubeId: "s4G7yTgV8Es",
    addedByUser: false,
  },
  {
    title: "Euterpe",
    artist: "EGOIST",
    animeName: "Guilty Crown",
    type: "ED",
    youtubeId: "rdIjGVefDuA",
    addedByUser: false,
  },
  {
    title: "Mephisto",
    artist: "Queen Bee",
    animeName: "Oshi no Ko",
    type: "ED",
    youtubeId: "z38PUYv5t4k",
    addedByUser: false,
  }
];
