import { AnimeTrack } from './types';

export const SEEDED_TRACKS: Omit<AnimeTrack, 'id' | 'elo' | 'matchesPlayed' | 'wins' | 'losses' | 'draws'>[] = [
  {
    title: "Specialz",
    artist: "King Gnu",
    animeName: "Jujutsu Kaisen Season 2",
    type: "OP",
    youtubeId: "Fv34w76a08A",
    addedByUser: false,
  },
  {
    title: "Bling-Bang-Bang-Born",
    artist: "Creepy Nuts",
    animeName: "Mashle: Magic and Muscles",
    type: "OP",
    youtubeId: "210R0ozmLwg",
    addedByUser: false,
  },
  {
    title: "Kura Kura",
    artist: "Ado",
    animeName: "Spy x Family",
    type: "OP",
    youtubeId: "vBstf_oIs-E",
    addedByUser: false,
  },
  {
    title: "Hollow Hunger",
    artist: "OxT",
    animeName: "Overlord IV",
    type: "OP",
    youtubeId: "l8YOnvG0s0w",
    addedByUser: false,
  },
  {
    title: "Inferno",
    artist: "Mrs. GREEN APPLE",
    animeName: "Fire Force",
    type: "OP",
    youtubeId: "wfCcs0vL7JA",
    addedByUser: false,
  },
  {
    title: "Guren no Yumiya",
    artist: "Linked Horizon",
    animeName: "Attack on Titan",
    type: "OP",
    youtubeId: "8OkpRKvqd8g",
    addedByUser: false,
  },
  {
    title: "We Are!",
    artist: "Hiroshi Kitadani",
    animeName: "One Piece",
    type: "OP",
    youtubeId: "9V-7mZ9lVsk",
    addedByUser: false,
  },
  {
    title: "Kizuna no Kiseki",
    artist: "MAN WITH A MISSION x milet",
    animeName: "Demon Slayer: Swordsmith Village Arc",
    type: "OP",
    youtubeId: "788D4bZ_iIs",
    addedByUser: false,
  },
  {
    title: "Peace Sign",
    artist: "Kenshi Yonezu",
    animeName: "My Hero Academia",
    type: "OP",
    youtubeId: "9aJVr5tTTWk",
    addedByUser: false,
  },
  {
    title: "Anytime Anywhere",
    artist: "milet",
    animeName: "Frieren: Beyond Journey's End",
    type: "ED",
    youtubeId: "anyJHe3sZsk",
    addedByUser: false,
  },
  {
    title: "Haruka Kanata",
    artist: "ASIAN KUNG-FU GENERATION",
    animeName: "Naruto",
    type: "OP",
    youtubeId: "nJ6A6GC_WF4",
    addedByUser: false,
  },
  {
    title: "Guren",
    artist: "DOES",
    animeName: "Naruto Shippuden",
    type: "OP",
    youtubeId: "X8c8_q6B9iM",
    addedByUser: false,
  },
  {
    title: "My Dearest",
    artist: "Supercell",
    animeName: "Guilty Crown",
    type: "OP",
    youtubeId: "DjUtmbZt8zc",
    addedByUser: false,
  },
  {
    title: "Cruel Clad in Scarlet",
    artist: "Yutaka Yamada",
    animeName: "Tokyo Ghoul",
    type: "OST",
    youtubeId: "zXQY6XvXfS0",
    addedByUser: false,
  },
  {
    title: "This Game",
    artist: "Konomi Suzuki",
    animeName: "No Game No Life",
    type: "OP",
    youtubeId: "CaksNMeGS-Y",
    addedByUser: false,
  },
  {
    title: "Colors",
    artist: "Flow",
    animeName: "Code Geass",
    type: "OP",
    youtubeId: "cZ7zQbM3C_I",
    addedByUser: false,
  },
  {
    title: "The Melancholy of Haruhi Suzumiya OST",
    artist: "Satoru Kousaki",
    animeName: "The Melancholy of Haruhi Suzumiya",
    type: "OST",
    youtubeId: "e7y1t6Z8Ksk",
    addedByUser: false,
  },
  {
    title: "Euterpe",
    artist: "EGOIST",
    animeName: "Guilty Crown",
    type: "ED",
    youtubeId: "3vV8r6kS-j4",
    addedByUser: false,
  },
  {
    title: "Mephisto",
    artist: "Queen Bee",
    animeName: "Oshi no Ko",
    type: "ED",
    youtubeId: "X8H0O1l2tO8",
    addedByUser: false,
  }
];
